<?php

namespace Bizzsol\RoleRegistry\Console;

use Illuminate\Console\Command;
use Symfony\Component\Finder\Finder;

/**
 * Part 1 (role decoupling) safety net: lists every place the code names a role literally, so the clean-up can be
 * done module by module and a test can fail the build when a new literal appears. Read-only.
 *
 *   php artisan roles:inventory [--markdown] [--json]
 */
class RoleLiteralInventory extends Command
{
    protected $signature = 'roles:inventory {--markdown : write docs/ROLE-LITERAL-INVENTORY.md} {--json : print the raw result as JSON}';

    protected $description = 'Report-only inventory of hard-coded role names (hasRole, hasAnyRole, role middleware, getManagerInfo, User::role)';

    /** @var array<string,string> pattern name => regex capturing the role argument(s) in group 1 */
    private const PATTERNS = [
        'hasRole' => '/hasRole\(\s*[\'"]([^\'"]+)[\'"]/',
        'hasAnyRole' => '/hasAnyRole\(\s*\[([^\]]*)\]/',
        'role middleware' => '/[\'"]role:([^\'"]+)[\'"]/',
        '@role blade' => '/@(?:role|hasrole|hasanyrole)\(\s*[\'"]([^\'"]+)[\'"]/i',
        'User::role' => '/::role\(\s*(\[[^\]]*\]|[\'"][^\'"]+[\'"])/',
        'getManagerInfo' => '/getManagerInfo\(\s*[\'"]([^\'"]+)[\'"]/',
        'Role::where name' => '/Role::where\(\s*[\'"]name[\'"]\s*,\s*[\'"](?!(?:=|!=|<>|like)[\'"])([^\'"]+)[\'"]/i',
    ];

    public function handle(): int
    {
        $files = Finder::create()->files()->in(array_filter([base_path('app'), base_path('Modules'), base_path('routes'), base_path('resources')], 'is_dir'))
            ->name('*.php')->notName('RoleLiteralInventory.php')->notPath('vendor')->notPath('node_modules')->notPath('database');

        $byRole = [];
        $byPattern = [];
        $byFile = [];

        foreach ($files as $file) {
            $rel = str_replace(base_path().'/', '', $file->getRealPath());
            foreach (preg_split('/\R/', $file->getContents()) as $i => $line) {
                if (preg_match('#^\s*(//|\*|/\*|\{\{--)#', $line)) {
                    continue; // comments
                }
                foreach (self::PATTERNS as $name => $regex) {
                    if (! preg_match_all($regex, $line, $m)) {
                        continue;
                    }
                    foreach ($m[1] as $arg) {
                        preg_match_all('/[\'"]([^\'"]+)[\'"]/', $arg, $names);
                        $roles = $names[1] ?: [trim($arg)];
                        foreach ($roles as $role) {
                            $byRole[$role] = ($byRole[$role] ?? 0) + 1;
                        }
                        $byPattern[$name] = ($byPattern[$name] ?? 0) + 1;
                        $byFile[$rel][$name] = ($byFile[$rel][$name] ?? 0) + 1;
                    }
                }
            }
        }

        arsort($byRole);
        uasort($byFile, fn ($a, $b) => array_sum($b) <=> array_sum($a));
        // getManagerInfo('Name', ...) already resolves the name through the RoleRegistry, so a role bound to that key works there.
        $registryBacked = $byPattern['getManagerInfo'] ?? 0;
        $result = ['hardcoded' => array_sum($byPattern) - $registryBacked, 'registry_backed' => $registryBacked,
            'total' => array_sum($byPattern), 'files' => count($byFile), 'by_role' => $byRole, 'by_pattern' => $byPattern, 'by_file' => array_map('array_sum', $byFile)];

        if ($this->option('json')) {
            $this->line(json_encode($result, JSON_PRETTY_PRINT));

            return self::SUCCESS;
        }

        $md = $this->markdown($result, $byFile);
        if ($this->option('markdown')) {
            file_put_contents(base_path('docs/ROLE-LITERAL-INVENTORY.md'), $md);
            $this->info('Wrote docs/ROLE-LITERAL-INVENTORY.md');
        }
        $this->line("{$result['hardcoded']} hard-coded role checks (+ {$result['registry_backed']} registry-backed getManagerInfo names) in {$result['files']} files");
        foreach (array_slice($byRole, 0, 12, true) as $role => $n) {
            $this->line(sprintf('  %-22s %d', $role, $n));
        }

        return self::SUCCESS;
    }

    private function markdown(array $r, array $byFile): string
    {
        $md = "# Role literal inventory\n\nGenerated by `php artisan roles:inventory --markdown` (report only). Comments are skipped.\n\n";
        $md .= "**{$r['hardcoded']}** hard-coded role checks that bypass the role registry, plus **{$r['registry_backed']}** `getManagerInfo('Name')` calls that already resolve through it, in **{$r['files']}** files. `tests/Feature/RoleLiteralRatchetTest.php` fails if the hard-coded number goes above zero.\n\n## By pattern\n\n| Pattern | Count |\n|---|---|\n";
        foreach ($r['by_pattern'] as $p => $n) {
            $md .= "| `{$p}` | {$n} |\n";
        }
        $md .= "\n## By role name\n\n| Role | Count |\n|---|---|\n";
        foreach ($r['by_role'] as $role => $n) {
            $md .= "| {$role} | {$n} |\n";
        }
        $md .= "\n## By file (top 40)\n\n| File | Count | Patterns |\n|---|---|---|\n";
        foreach (array_slice($byFile, 0, 40, true) as $file => $patterns) {
            $md .= "| `{$file}` | ".array_sum($patterns).' | '.implode(', ', array_map(fn ($k, $v) => "{$k}×{$v}", array_keys($patterns), $patterns))." |\n";
        }

        return $md;
    }
}
